### ISSUE TITLE
Pass Rosetta API tests

### ISSUE THREAD

**Issue by jels-boolean** [monadicus/mentat#2]
This involves filling in the logic for the currently standing endpoints and then writing tests that confirm proper functionality.

We can use bitcoin data for now:

- [x] Run [rosetta-bitcoin](https://github.com/jels-boolean/rosetta-bitcoin) locally.
- [x] Depends on #9.
- [x] pass rosetta-cli tests with bitcoin

**Comment by mowkoshka** [comment]
Time Estimate: depends on subtasks

**Comment by mowkoshka** [comment]
Time taken so far: 9 hours
