### ISSUE TITLE
[Bug] Node always needs to be launched

### ISSUE THREAD

**Issue by mowkoshka** [monadicus/mentat#72]
## 🐛 Bug Report

The node should always be launched, but it is only launched during online mode.

## Steps to Reproduce

Launch node in offline mode and you cannot make any rpc calls.

## Code/Action snippet to reproduce

(https://github.com/monadicus/mentat/blob/main/mentat/src/server/mod.rs#L143)

## Expected Behavior

RPC calls should work as long as they don't make any outbound connections.

(Write what you expected to happen here)

## Your Environment

- Mentat Version: Main

**Comment by Meshiest** [comment]
I thought this was intended so you could have configs that didn't need to start child processes?

**Comment by mowkoshka** [comment]
@Meshiest iirc according to what @MACS-J1149 and I found the node always needs to be started according to Rosetta spec. It's just that in OFFLINE mode outbound connections are not allowed.
