### ISSUE TITLE
[Bug] Configuration Template Generation Fails

### ISSUE THREAD

**Issue by mowkoshka** [monadicus/mentat#99]
## 🐛 Bug Report

Generating a templated configuration file for mentat's rosetta-snarkos fails.

## Code/Action snippet to reproduce

`cargo run ./conf.dne.toml`

## Stack trace & error message

```
thread 'main' panicked at 'Failed to create default toml configuration at `./conf2.toml`: unsupported Rust type', C:\Users\jonat\AppData\Roaming\work\Monadicus\mentat\mentat\src\conf\configuration.rs:195:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected Behavior

Should generate the configuration file.

**Comment by MACS-J1149** [comment]
still an issue with mixed type tuple structs, but thats an issue in toml itself
